## we will start with pandas
#we will start with series, and dataframes, and learn about more as we go on

In [1]:
import numpy as np #since numpy is core library
import pandas as pd
from pandas import Series, DataFrame
#series is like dicitonary, so it's possible to interconvert both of them
a = Series([1,2,3,4,5],index=["one","two","Three","Four","Five"])
#one part is values and another is index
print(a)
#we can access only values and index, by calling as method
print(a.values)
print(a.index)
#to conver a dic to Series and vice versa
b = a.to_dict()
print(b)
c = Series([7], index=["one","Two"])
#value cannot be more than index, if index is provided
d = a + c
print(d)
#another thing is Series has a name other than object name
a.name = "Holla" #this are methods, It always in last 
a.index.name = "sanji" #this are methods, and It's not applicable for values
print(a)

one      1
two      2
Three    3
Four     4
Five     5
dtype: int64
[1 2 3 4 5]
Index(['one', 'two', 'Three', 'Four', 'Five'], dtype='object')
{'one': 1, 'two': 2, 'Three': 3, 'Four': 4, 'Five': 5}
Five     NaN
Four     NaN
Three    NaN
Two      NaN
one      8.0
two      NaN
dtype: float64
sanji
one      1
two      2
Three    3
Four     4
Five     5
Name: Holla, dtype: int64


In [ ]:
## Operations on dataframes and understanding
fra = pd.read_clipboard()
#print(fra) #print formats object as string to display, so it may lose some fatures

print(fra.Won)#we can use dot method or list method, better use list method to access data column

#so data frame is like spread sheet with columns indicating name of that coloumn
#we cannot have paragraph as data frame till i have learned.
#we want to grab multiple column from dataframe
##########****DataFrame(data_obj,columns=["c1","c2"]) it will grab only this column
fra.head(2)# dataframe_obj.head(n) displays rows from start
fra.tail(2)#from last
fra.ix[3] #index pre assigned number by pandas starting from 0
fra["Rank"] # this is row we access each column head values
fra["Birth"] = np.array([22,23,1,3,4,8,9]) #This way we can add one more column
print(fra)
#series have default index of 0..N so does dataframes, SO we can add series to data frames
# lets say dataframes as column named color, and series has yeloow, blue with index 0,1
lol = Series(["Red","Blue"], index=[2,5])
print(lol)
fra['color'] = lol
print("{}".format(fra),end="")
#we can delete particular column by ### del dataframe_object["column_name]

In [20]:
_a = Series(["a","b","c","d"],index=[1,2,3,4])
print(_a)
_a[2]="n"
print(_a)
_b = _a.index
# print(_b[3])
# _b[3] = "k" this fails for simple reason that _b is still pointingf towards _a
_b = Series([1,7,8,9])#when _b is constructed newly it doesn't points
#the above reasoning is incomplete, _a.index when passed to other object, it becomes immutable
_b[3]="n"
print(_b)


1    a
2    b
3    c
4    d
dtype: object
1    a
2    n
3    c
4    d
dtype: object
0    1
1    7
2    8
3    n
dtype: object


In [3]:
#reindexing

# _b = _a #_b points towards _a
# _b = _a.index #only index value is being pointed
# _b = _a.reindex([11,12,13,14])#reindex creates different object
# print(_b,end="")
_c = np.array([1,2,3,44,23,21,76,33,90])
_d = _c.reshape((3,3))
print(_d,end="\n")
# _d.reindex(index=["A","B","C"], columns=["a","b","c"])****this is wrong way since it's not dataframe
df = DataFrame(_d,index=["A","B","C"], columns=["a","b","c"])
df=df.reindex(index=["A","B","C","D","E"], columns=["a","b","c","d"])#when we use method to mutate the object, we must assign to a different object or itself
df
#shortcut of reindex is .ix[]
df2 = DataFrame(df)
df2 = df2.ix[["A","B","D"],["a","b","d"]]#when using ix, one parameter is index values, and another is columns
_q = Series(["23","24","25"],index=["A","B","D"])
df2["d"] = _q
q = Series(["23","24"],index=["a","b"])
df2.ix["D"]= q
df2["d"].ix["D"]=34 #this is how we add individual values
df2.ix["D","d"] = 50 #typical reindex way
df2>20
## boolean dataframe value,
#df2>20 #the entery will show true or false
#THe default indexing will be present, if index is named with string



[[ 1  2  3]
 [44 23 21]
 [76 33 90]]


a     b     d
A  True  True  True
B  True  True  True
D  True  True  True

## Drop from series or data frame
we can use series_obj.drop(index_name)
on data frame
dataframe_obj.drop(indexname) if we want to drop  row
but if we want to drop column, then
dataframe_obj.drop(column_nmae, axis=1), axis = 0 refers horizontal, and 1 refers vertical

### pandas can add two or more series with same index, and If with unequal length of index then It will give NaN 
we can sort a series by index using method -->  series_obj.sort_index()
we can sort by values using method --> series_obj.sort_values()
ranking 0 is for lowest to biggest value as last rank using method series.rank()
# Below are some methods perform on DataFrame


In [25]:
_q1 = np.array([[1,2,3],[4,5,6],[9,8,1]])
# print(_q1.sum()) when array or matrix is .sum() all values are added
#but different in dataframe
_df3 = DataFrame(_q1,columns=["A","B","C"])
_df3.sum() #by default it sums according to column or axis 0
#we can show sum according to axis 1 or index
_df3.sum(axis=1)
_q1.min()
# method .min() and max() are applicable on column like mentioned above
#to find index of min value in column, we can use method .idxmin()
_df3.idxmin()#it gives columna and index where min value lies, index can be repetitive but not column
# method .cumsum() to calculate cumalative sum in column
#cumlative sum is, a,a+b,a+b+c....
_q2 = np.array([["a","h","c"],["d","e","f"],["d","h","i"]])
_df4 = DataFrame(_q2,columns=["A","B","C"])
_df4.describe()#even when elemnst are string it works, It describes every detail about that column
_df4.cumsum()#even when elemnst are string it works
_df4.sum()#even when elemnst are string it works
#all methods which work on int element won't work on string, Values are not converted to ASCII
_df3.describe()#count is number of element in that column


A    B         C
count  3.000000  3.0  3.000000
mean   4.666667  5.0  3.333333
std    4.041452  3.0  2.516611
min    1.000000  2.0  1.000000
25%    2.500000  3.5  2.000000
50%    4.000000  5.0  3.000000
75%    6.500000  6.5  4.500000
max    9.000000  8.0  6.000000

In [44]:
#to find missing value location in a column we can ask df_obj.isnull()
#To drop all NaN we can use df_obj.dropna() && dropna(how='all') to drop anrow with all NaN value
_q5 = np.array([["a","h",np.nan],["d","np.nan","f"],["d",np.NaN,np.NaN]])
df5=DataFrame(_q5,columns=["A","B","C"])
df5=df5.reindex(index=[1,2,3,4],columns=["A","B","C","D"])#couldn't get NaN, so used reindex
df5=df5.dropna(thresh=2)#considers row not column
df5.fillna(66)

A       B    C   D
1  d  np.nan    f  66
2  d     nan  nan  66

In [39]:
#Multi-level index
_q6 = np.arange(9)
_s1 = Series(_q6,index=[[1,1,1,2,2,2,3,3,3],["a","b","c","a","b","c","a","b","c"]])
_s1
_s1[1,"c"]#Series and other may have index as first
_df6 = DataFrame(_s1, columns=["Number"])
_df6["Number"].ix[:,"b"]#but dataframe have column or axis 0
#Another way to dataframe, is converting multi-level series to dataframe using method  .unstack
_df7 = _s1.unstack() #Notice above _df6 and _df7 are both dataframe, but different
#_df7 is more like meshgrid matrix, rather traditional dataframe, but still dataframe
_1q = np.array(["nil","es","h"])
_df7["c"] = _1q
_df7
#_df7 = _df7.ix[[[1,1,2],["a","b","a"]],[["integers","integers","string"],[0,1,3]]] 
_df7 = _df7.reindex(index=[[1,1,2],["a","b","a"]],columns=[["integers","integers","string"],[0,1,3]])
#while reindexing care needs to be taken that the format of index isn't changed or values will be lost
_df8 = DataFrame(_q6.reshape((3,3)),index=[[1,1,2],["a","b","a"]],columns=[["integers","integers","string"],[0,1,3]])
_df8["string"]=_1q
_df8

#what if we need to give title to the index or column
_df8.index.names = ["ix1","ix2"]
_df8.columns.names = ["string title","integer title"]
_df8.swaplevel("string title","integer title",axis=1)
#################################******swaplevel needs axis=1 along column, didn't understood
_df8.swaplevel("ix1","ix2",axis=0)
#######npt tested method on dataframe of multi level
# .sortlevel(n) where n(- 0,1; 0 for outer level


string title  integers    string
integer title        0  1      3
ix2 ix1                         
a   1                0  1    nil
b   1                3  4     es
a   2                6  7      h